rookie:
  port: 9000
  bossThreadSize: 1
  workThreadSize: 8
  ##redis
  redis:
    mode: single
    database: 0
    password:
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: localhost:6379

  rabbitmq:
    host: #${rabbitmq.host}
    port: #${rabbitmq.port}
    virtualHost: /
    username: #${rabbitmq.username}
    password: #${rabbitmq.password}
